### ISSUE TITLE
Image cant working

### ISSUE THREAD

**Issue by TheGuest0** [PolarisPyra/CozyNetwork#10]
![PXL_20231207_021650706.jpg](https://github.com/PolarisPyra/CozyNetwork/assets/153145104/c5ce9a54-5245-4abb-814d-621d5d6a51ed)

![PXL_20231207_021629189~2.jpg](https://github.com/PolarisPyra/CozyNetwork/assets/153145104/dd771d92-538f-4d8a-975b-be07626066c3)

![07ff1b2e-ead8-4e00-ac5a-4265c8a1130b.jpg](https://github.com/PolarisPyra/CozyNetwork/assets/153145104/840372eb-c80d-4042-90f3-2cfd0652c934)

**Comment by PolarisPyra** [comment]
So you actually no longer need accessCode but you do need these three .env
JWT_SECRET=strongsecret
NEXT_PUBLIC_ARTEMIS_API_URL=http://localhost:4000
NEXT_PUBLIC_CDN=folderforimages

also for the cdn just make it be public/

**Comment by PolarisPyra** [comment]
by the way JWT_SECRET=strongsecret NEEDS to be the same for the artemisapi and the frontend. Make sure you're running the latest code base please.

**Comment by PolarisPyra** [comment]
woops just realized i closed this my bad

**Comment by TheGuest0** [comment]
> So you actually no longer need accessCode but you do need these three .env
> JWT_SECRET=strongsecret
> NEXT_PUBLIC_ARTEMIS_API_URL=http://localhost:4000
> NEXT_PUBLIC_CDN=folderforimages
> 
> also for the cdn just make it be public/ 

![PXL_20231207_025013568.jpg](https://github.com/PolarisPyra/CozyNetwork/assets/153145104/2fcb33e4-1a83-43a2-936c-4bfe2134e1e3)

![PXL_20231207_024943750.MP.jpg](https://github.com/PolarisPyra/CozyNetwork/assets/153145104/ed30085e-054c-4f73-bdaa-56e245ec6bc3)

**Comment by PolarisPyra** [comment]
please give me a little while to test a solution but in the mean time can you try just making the link be / and not public/

**Comment by PolarisPyra** [comment]
the front end is cozynet the backend is artemis api

**Comment by TheGuest0** [comment]
> please give me a little while to test a solution but in the mean time can you try just making the link be / and not public/

It worked now by change to / thx!

**Comment by TheGuest0** [comment]
> hey sorry i couldnt help but notice your max rating is 20.01? did you somehow edit the db to change your rating at one point? 

Idk 
i was change db.sqlite when i use aqua
but now idk how to edit on Artemis 
I can't find Artemis db sqlite
