### ISSUE TITLE
datagrabber.py is not working

### ISSUE THREAD

**Issue by TheGuest0** [PolarisPyra/CozyNetwork#8]
![PXL_20231207_005613144](https://github.com/PolarisPyra/CozyNetwork/assets/153145104/6c06c96c-1e00-42a8-9e61-339fd5094157)

**Comment by PolarisPyra** [comment]
Can i see the layout of your Chunithm folder please? Also can you try the command without any Chinese characters in the path name?

**Comment by TheGuest0** [comment]
> Can i see the layout of your Chunithm folder please? Also can you try the command without any Chinese characters in the path name? 

![PXL_20231207_011810477.jpg](https://github.com/PolarisPyra/CozyNetwork/assets/153145104/5fcd1694-57bf-4849-ba22-b526b9904296)

![PXL_20231207_011909446.jpg](https://github.com/PolarisPyra/CozyNetwork/assets/153145104/a65ae638-71eb-48b7-9c90-6efc4892f351)

**Comment by PolarisPyra** [comment]
Can you try moving your options folder into "\App\bin\" since that is where it expects the options folder to be you can move it back when you're done. 

also make sure you are on python 3.12 with pip tqdm installed.

**Comment by TheGuest0** [comment]
Fixed Thank you!

**Comment by PolarisPyra** [comment]
real quick, was it the moving of the options folder that fixed it?
